# Generated by Django 5.2.4 on 2025-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Users Helped'", max_length=100)),
                ('value', models.CharField(help_text="e.g., '10,000+'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='partner_logos/')),
                ('website_url', models.URLField(blank=True)),
                ('tier', models.CharField(choices=[('FOUNDING', 'Founding Partner'), ('SUPPORT', 'Supporter')], default='SUPPORT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="e.g., 'fa-gavel' for a Font Awesome icon", max_length=50)),
                ('description', models.TextField()),
                ('tool_url', models.URLField()),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('SOON', 'Coming Soon')], default='LIVE', max_length=4)),
                ('order', models.PositiveIntegerField(default=0, help_text='Used to order tools on the homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
